import { boot, frames, exec } from "./b_lib";
boot(["-basedir","/home/buzzkill/Projects/qfiles/q1-basedir","-game","e2e_b","-nosound"]);
frames(5);
console.log("MARK load1");
exec("map e1m1", 30);
console.log("MARK load1done");
console.log("MARK load2");
exec("map e1m1", 30);
console.log("MARK load2done");
process.exit(0);
